### ISSUE TITLE
-a parameter doesnt accept the full path of the artifac file.

### ISSUE THREAD

**Issue by fafiorim** [tclahr/uac#154]
the artifact parameter doesn't accept the entire file path of the file. For manual execution works file, but when automating it could became a challenge, since is better to avoid the using of the cd command.

Error e.g.:
# /tmp/uac/uac-main/uac -a /tmp/uac/uac-main/artifacts/memory_dump/avml.yaml /tmp
uac: artifact file not found '/tmp/uac/uac-main/artifacts//tmp/uac/uac-main/memory_dump/avml.yaml'

Works with when in the same directory:
e.g.:
# pwd
/tmp/uac/uac-main
# /tmp/uac/uac-main/uac -a artifacts/memory_dump/avml.yaml /tmp

**Comment by tclahr** [comment]
By default, UAC will search for artifacts within "artifacts" directory only. I have added this enhancement to the development road map. Thank you!

**Comment by tclahr** [comment]
This feature requires changes on how UAC store collected data. Today, UAC stores live data into a directory structure following the same structure in the artifacts directory. If an artifact file is located outside UAC directory, UAC would never know where to store the collected data.

I.e.: artifact files located in 'artifacts/live_response/hardware' will always store data into 'live_response/hardware' directory, and so on. If an artifact file is located in /tmp/my_custom_artifact_files/custom.yaml, UAC will never know where to store that data in the output file.

In UAC v3, setting the 'output_directory' property will be required in YAML files, so no matter where the YAML file is, UAC will always know where to store the data properly. This also brings more flexibility for collecting and storing artifacts.

**Comment by tclahr** [comment]
I have pushed a new code to develop that makes this possible.
- Now you have the option to supply a file path to a custom profile located outside the profiles directory.
- Now you have the option to supply a file path to a custom artifact located outside the artifacts directory.

To make this possible **output_directory** property must be set.

Can you download the develop branch and test it, please?

**Comment by tclahr** [comment]
Code has been merged and released in uac v3.0.0-rc1.
