### ISSUE TITLE
Collect wget artifact

### ISSUE THREAD

**Issue by firexfly** [tclahr/uac#182]
Wget is a well-known command line download utility, installed by default on many Linux distros and Solaris and available as a package on FreeBSD etc.

When a host is HSTS compliant, the wget HSTS cache (`~/.wget-hsts`) stores the last time - in epoch time - that wget was used to access the host along with the hostname.

I would like to create a PR to add the wget-hsts file to UAC because it can be useful for triage during IR engagements.

e.g. `artifacts/files/applications/wget-hsts`

Reference: [My blog post from a couple years ago](https://firexfly.com/wget-hsts/)

**Comment by tclahr** [comment]
Hello,

Sure. Just follow these instructions -> https://github.com/tclahr/uac/blob/main/CONTRIBUTING.md
Please submit your PR to the ```develop``` branch.

I recommend you create a new artifact file in ```artifacts/files/applications/wget``` as the file .wget-hsts is part of the wget tool.

Thank you!

**Comment by tclahr** [comment]
Merged into develop
