### ISSUE TITLE
Docker.yaml - docker stats ContainerId run into loop

### ISSUE THREAD

**Issue by tuzux8** [tclahr/uac#237]
identified that the "docker stats <containerID>" command runs in a loop and therefore the program is not terminated.

tested it with Amazon Linux. Collection works fine after removing this lines.

**Comment by tclahr** [comment]
Confirmed. I will release a new version fixing it tonight. It also affects podman.yaml

**Comment by tclahr** [comment]
UAC v2.9.1 was just released with the fix. Thanks for reporting it.
