### ISSUE TITLE
Systemd config file directory for collection is missing

### ISSUE THREAD

**Issue by mnrkbys** [tclahr/uac#247]
The systemd configuration directories for collection are defined in systemd.yaml. However, only two direcotries are defined.
Actually, systemd configuration files can be placed in various directories.
For example, on [SANS SIFT Workstation](https://www.sans.org/tools/sift-workstation/) (based on Ubuntu 20.04), we can place the following directories.

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ systemd-analyze unit-paths
/etc/systemd/system.control
/run/systemd/system.control
/run/systemd/transient
/run/systemd/generator.early
/etc/systemd/system
/etc/systemd/system.attached
/run/systemd/system
/run/systemd/system.attached
/run/systemd/generator
/usr/local/lib/systemd/system
/lib/systemd/system
/usr/lib/systemd/system
/run/systemd/generator.late

$ systemd-analyze unit-paths --user
/home/sansforensics/.config/systemd/user.control
/run/user/1000/systemd/user.control
/run/user/1000/systemd/transient
/run/user/1000/systemd/generator.early
/etc/xdg/xdg-ubuntu/systemd/user
/etc/xdg/systemd/user
/home/sansforensics/.config/systemd/user
/etc/systemd/user
/run/user/1000/systemd/user
/run/systemd/user
/run/user/1000/systemd/generator
/home/sansforensics/.local/share/systemd/user
/usr/share/ubuntu/systemd/user
/usr/local/share/systemd/user
/usr/share/systemd/user
/var/lib/snapd/desktop/systemd/user
/usr/local/lib/systemd/user
/usr/lib/systemd/user
/run/user/1000/systemd/generator.late
```

I believe that UAC should at least collect files in the previous directories.
What do you think?

**Comment by tclahr** [comment]
I checked the default locations for several linux flavors such as alma linux, debian, ubuntu, arch linux, oracle linux, fedora, red hat, clear linux and suse linux. They have pretty similar (not to say the same) locations set for both system and per-user configuration files.
I have updated files/system/systemd.yaml to add any missing locations based on the tests on the systems above.

**Comment by mnrkbys** [comment]
Great! Thanks for considering it.
