### ISSUE TITLE
Suggestion: add basic command artifacts to ir_triage.yaml

### ISSUE THREAD

**Issue by mnrkbys** [tclahr/uac#275]
I believe that only the minimum necessary artifacts are defined in `ir_triage.yaml`.
Although `file/applications/*` is configured to be excluded, `wget` (wget.yaml) and `vim` (viminfo.yaml) are very basic commands and should be included in `ir_triage.yaml`.
If you would consider merging PR #274, it would be better to include it as well.

**Comment by tclahr** [comment]
Yes, I agree. I will add them to `ir_triage` profile.

**Comment by tclahr** [comment]
Merged into develop branch.
