### ISSUE TITLE
Redundant artifacts in artifacts/files/system/var_spool.yaml and artifacts/files/system/job_scheduler.yaml

### ISSUE THREAD

**Issue by mnrkbys** [tclahr/uac#285]
The job_scheduler.yaml has the following artifacts:

```
  -
    description: Collect at files.
    supported_os: [aix, freebsd, linux, netbsd, netscaler, openbsd, solaris]
    collector: file
    path: /var/spool/at
  -
    description: Collect at files.
    supported_os: [aix, freebsd, linux, netbsd, netscaler, openbsd, solaris]
    collector: file
    path: /var/spool/cron
```

Additionally, var_spool.yaml also has the following artifact:

```
  -
    description: Collect spool files.
    supported_os: [aix, esxi, freebsd, linux, netbsd, netscaler, openbsd, solaris]
    collector: file
    path: /var/spool
```

Since the var_spool.yaml artifact contains the scope of job_scheduler.yaml, it could be integrated into var_spool.yaml.

**Comment by tclahr** [comment]
There are intersections between both, but for instance, `job_scheduler.yaml` has some artifacts not related to /var/spool such as `/var/adm/cron`.

In the other side, `/var/spool` can include cups and mail files for instance.

UAC will dedup and collect the files only once.

**Comment by mnrkbys** [comment]
Thanks for explaining the difference between the two.
I also understand the process regarding deduplication.
I will close this issue.
