### ISSUE TITLE
Document which collectors exist

### ISSUE THREAD

**Issue by q2dg** [tclahr/uac#286]
In https://tclahr.github.io/uac-docs/artifacts/#artifacts-definition it is said: "UAC reads the YAML files dynamically and, based on their contents, uses one of the five available collectors to collect the relevant artifacts." But there's no place where these five collectors are listed and described. Explanation of"collector" keyword it's just this: "UAC uses collectors to gather data, with each collector serving a specific function and requiring its options". I think that there should be shown the list of the five collectors ("command", "hash", "file", "find", "stat"??)  with a brief description. 
Thanks!

**Comment by tclahr** [comment]
Done!
