### ISSUE TITLE
Missing _file_collector Function in Main Branch

### ISSUE THREAD

**Issue by Zagreb-cmd** [tclahr/uac#289]
Hello,

I encountered an issue in the main branch code where the function `_file_collector` is referenced in the _parse_artifact function, but there is no definition for `_file_collector` in the codebase. Instead, I noticed that `_find_based_collector` seems to perform similar functionality, based on the parameters it accepts.

Could you confirm if this is an error or an intentional change? If `_file_collector` was renamed to `_find_based_collector`, should we update the references accordingly?

Thank you for your assistance!

**Comment by tclahr** [comment]
`_file_collector` was replaced by `_find_based_collector` in UAC v3. This bug affects artifacts that either hash or stat files within user's home folder.
Currently, neither bodyfile.yaml nor hash_executables.yaml uses %home_user% variable, but this can affect custom artifacts created by users.

**Comment by tclahr** [comment]
Fixed in PR #290
