### ISSUE TITLE
Order of volatility

### ISSUE THREAD

**Issue by deeFIR** [tclahr/uac#46]
Is it possible to adjust the order of volatility with respect to memory acquisition with AVML? Memory should be collected first, and then artifacts contained within the specified profile.

`Note that when a profile and a list of artifacts are provided, the artifacts from the profile will always be collected first, even if the parameter -a was provided before -p in the command line. In the example below, the memory_dump/avml.yaml artifact will only be collected after all artifacts from full profile were collected.`

`./uac -a memory_dump/avml.yaml -p full /tmp`

**Comment by tclahr** [comment]
You can now use as many --artifacts (-a) and --profile (-p) as you want to build an even more customized collection. Artifacts will be collected in the order they were provided in the command line. Example:

```shell
./uac -a memory_dump/avml.yaml -p ir_triage -p my_custom_profile01 -a \!bodyfile/bodyfile.yaml /tmp
```

code has been pushed to the develop branch. Can you test it, please?

**Comment by tclahr** [comment]
Fixed and merged into develop branch.
PR #71
