### ISSUE TITLE
Execution via EDR

### ISSUE THREAD

**Issue by John-Crabb** [tclahr/uac#47]
I have noticed an issue when executing UAC via our EDR.  It will not pull back all of the user data from  `/home`

I see the following in the **uac.log.stderr**

`./uac: 95: HOME: parameter not set`
`./uac: 95: HOME: parameter not set`

I was able to recreate this on multiple Linux Distros (Ubuntu 20 LTS and CentOS 7).  Running the script via terminal directly on the host everything works as expected.

The EDR will execute the script as **root**

I have tried to identify what portion of UAC is causing the above error but have not been able to find it.  I was hoping to find the issue, and just give you the fix.

I am happy to help or test in any way you need.

**Comment by tclahr** [comment]
Hi John,
Are you running uac v2.1? Can you test v2.2-rc1? Also, can you run it again using --debug and provide me the uac.log file pls?
Thanks!

**Comment by John-Crabb** [comment]
Hi Thiago,
I had tested with v2.1 and v2.2-rc2.  Just ran it again with v2.2-rc1 w/ debug and the issue persists.  I'll include the uac.log and the uac.log.stderr

[logs.zip](https://github.com/tclahr/uac/files/8555151/logs.zip)

Thanks for the quick response!

**Comment by tclahr** [comment]
As UAC uses "set -u" as a best programming practice, the function get_user_home_list() exits with errors when the system HOME variable is not set.
I noticed that in some situations where the system HOSTNAME variable is not set, get_hostname() function can also exit with errors.

I have added a small code to the main uac script to set both HOME and HOSTNAME before "set -u".

Can you replace the existing uac with the one attached below and test it again pls? Thanks!

[uac.zip](https://github.com/tclahr/uac/files/8562400/uac.zip)

**Comment by John-Crabb** [comment]
Looks like the issue persists.  I am getting the `.cache` directory and the `.local` directory, but that is the only data under the home directory for the single user on this Ubuntu 20.04 LTS test system.  Attaching logs, let me know if you need me to try anything else.
[patched_uac_0426.zip](https://github.com/tclahr/uac/files/8564993/patched_uac_0426.zip)

**Comment by tclahr** [comment]
My bad. I provided the wrong file. Try this one for v2.2.0-rc1. Thanks!

[uac_2.2.0-rc1.zip](https://github.com/tclahr/uac/files/8571069/uac_2.2.0-rc1.zip)

**Comment by John-Crabb** [comment]
Hi Thiago,

No worries on the wrong version. This version won't run at all, it errors out on line 104:

`./uac: 104: HOME: parameter not set`

So no logs to send you.

I took a look at the set environment variables for the EDR session and this is the output of `printenv` command:

`PWD=/tmp/uac-release-2.2.0-rc1`
`_=/usr/bin/printenv`
`SHLVL=0`

I attempted to set the variable by hand but that did not work.  Wondering if pulling the data out of `passwd` would work?  You may be doing this in the collectors, so feel free to ignore that comment.  :) 

BTW, I am part of the DFIR Discord server.  If it is easier to have a conversation there, just say the word.

**Comment by tclahr** [comment]
yes, ping me there pls! tclahr

**Comment by tclahr** [comment]
Fixed and merged into v2.2.0
